version: 2
updates:
- package-ecosystem: npm
  directory: "/site"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/site/concept"
  schedule:
    interval: monthly
  open-pull-requests-limit: 99
